"""create jobs and hr related tables

Revision ID: 289ff8f18df2
Revises: ae36361dfc8a
Create Date: 2026-02-19 01:04:37.666185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289ff8f18df2'
down_revision: Union[str, Sequence[str], None] = 'ae36361dfc8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_briefings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('extracted_fields', sa.JSON(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('audio_file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_briefings_id'), 'hr_briefings', ['id'], unique=False)
    op.create_table('evaluation_chats',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('job_descriptions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('job_summary', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.JSON(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('jd_file_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('role_hr_briefings',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('briefing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['briefing_id'], ['hr_briefings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'briefing_id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('fit_score', sa.Integer(), nullable=True),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('concerns', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('candidate_responses', sa.JSON(), nullable=True),
    sa.Column('interview_completed', sa.String(length=50), nullable=True),
    sa.Column('audio_file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'candidate_id', name='_role_candidate_uc')
    )
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_table('role_hr_briefings')
    op.drop_table('job_descriptions')
    op.drop_table('evaluation_chats')
    op.drop_index(op.f('ix_hr_briefings_id'), table_name='hr_briefings')
    op.drop_table('hr_briefings')
    # ### end Alembic commands ###
