"""Rename year_of_experience to years_of_experience in candidates table

Revision ID: 53b209d0aa50
Revises: fe6fb4b33e2b
Create Date: 2026-02-13 20:20:12.941056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b209d0aa50'
down_revision: Union[str, Sequence[str], None] = 'fe6fb4b33e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    op.drop_column('candidates', 'year_of_experience')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('year_of_experience', sa.INTEGER(), nullable=True))
    op.drop_column('candidates', 'years_of_experience')
    # ### end Alembic commands ###
